ARG PYTHON_VERSION=3.12
FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-bookworm-slim AS base

ENV PYTHONUNBUFFERED=1

ARG UID=10001
RUN adduser \
  --disabled-password \
  --gecos "" \
  --home "/app" \
  --shell "/sbin/nologin" \
  --uid "${UID}" \
  appuser

RUN apt-get update && apt-get install -y \
  gcc \
  g++ \
  python3-dev \
  libglib2.0-0 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN mkdir -p src

RUN uv sync --locked --no-install-project

COPY . .

RUN uv sync --locked

RUN chown -R appuser:appuser /app

USER appuser

RUN uv run agent download-files

EXPOSE 8000

CMD ["uv", "run", "agent", "start"]
